/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { SimulationConfig } from '../types';

const baseConfig: Omit<SimulationConfig, 'id' | 'name' | 'nuanceDescription'> = {
  shapeType: 'square',
  vertexCount: 4,
  gravity: 0.15,
  friction: 0.001,
  restitution: 0.8,
  rotationSpeed: 0.005,
  ballCount: 3,
  ballSize: 8,
  initialSpeed: 5,
};

export const presets: SimulationConfig[] = [
  {
    ...baseConfig,
    id: 1,
    name: "标准正方形",
    shapeType: 'square',
    nuanceDescription: "经典物理环境，适中的重力和反弹效果。",
    rotationSpeed: 0.005,
  },
  {
    ...baseConfig,
    id: 2,
    name: "高重力三角形",
    shapeType: 'triangle',
    vertexCount: 3,
    gravity: 0.5,
    restitution: 0.6,
    nuanceDescription: "在狭窄空间内的沉重球体。",
    ballCount: 2,
  },
  {
    ...baseConfig,
    id: 3,
    name: "零重力六边形",
    shapeType: 'hexagon',
    vertexCount: 6,
    gravity: 0,
    friction: 0,
    restitution: 1.0,
    ballCount: 6,
    nuanceDescription: "无重力状态，完美的能量守恒运动。",
    rotationSpeed: 0.01,
  },
  {
    ...baseConfig,
    id: 4,
    name: "疾速旋转八边形",
    shapeType: 'octagon',
    vertexCount: 8,
    rotationSpeed: 0.04,
    gravity: 0.1,
    ballCount: 15,
    ballSize: 4,
    nuanceDescription: "大量微小粒子在离心力作用下的混乱表现。",
  },
  {
    ...baseConfig,
    id: 5,
    name: "粘性五边形",
    shapeType: 'pentagon',
    vertexCount: 5,
    restitution: 0.4,
    friction: 0.05,
    nuanceDescription: "低弹性环境，球体倾向于在表面滚动。",
  },
  {
    ...baseConfig,
    id: 7,
    name: "反向重力",
    shapeType: 'square',
    gravity: -0.1,
    ballCount: 5,
    nuanceDescription: "重力方向向上牵引。",
  },
  {
    ...baseConfig,
    id: 8,
    name: "强摩擦力",
    shapeType: 'hexagon',
    friction: 0.1,
    restitution: 0.5,
    rotationSpeed: 0.02,
    nuanceDescription: "球体在空气中会迅速减速。",
  },
  {
    ...baseConfig,
    id: 9,
    name: "粒子群落",
    shapeType: 'octagon',
    ballCount: 40,
    ballSize: 2,
    gravity: 0.05,
    nuanceDescription: "海量的微小粒子协同运动。",
  },
  {
    ...baseConfig,
    id: 10,
    name: "慢动作",
    shapeType: 'pentagon',
    initialSpeed: 1,
    gravity: 0.02,
    rotationSpeed: 0.002,
    nuanceDescription: "所有物体的移动都极其缓慢。",
  },
  {
    ...baseConfig,
    id: 11,
    name: "极限速度",
    shapeType: 'triangle',
    initialSpeed: 15,
    gravity: 0.3,
    restitution: 0.9,
    nuanceDescription: "发生极高速度的冲击与反弹。",
  },
  {
    ...baseConfig,
    id: 12,
    name: "巨型球体",
    shapeType: 'square',
    ballCount: 1,
    ballSize: 25,
    gravity: 0.4,
    nuanceDescription: "一个巨大的核心球体主宰着空间。",
  },
  {
    ...baseConfig,
    id: 13,
    name: "逆向旋转",
    shapeType: 'hexagon',
    rotationSpeed: -0.03,
    ballCount: 4,
    nuanceDescription: "容器正在快速逆时针旋转。",
  },
  {
    ...baseConfig,
    id: 16,
    name: "近乎永动机",
    shapeType: 'square',
    restitution: 0.95,
    ballCount: 4,
    nuanceDescription: "极高弹性，运动状态能维持很长时间。",
  },
  {
    ...baseConfig,
    id: 17,
    name: "拥挤之家",
    shapeType: 'triangle',
    ballCount: 10,
    ballSize: 10,
    nuanceDescription: "对该形状而言，球体数量过多且体积过大。",
  },
  {
    ...baseConfig,
    id: 18,
    name: "纳米粒子云",
    shapeType: 'hexagon',
    ballCount: 50,
    ballSize: 1.5,
    gravity: 0,
    initialSpeed: 8,
    nuanceDescription: "零重力下的微小纳米粒子云团。",
  },
  {
    ...baseConfig,
    id: 19,
    name: "慵懒旋转",
    shapeType: 'octagon',
    rotationSpeed: 0.001,
    gravity: 0.2,
    ballCount: 5,
    nuanceDescription: "几乎静止不动的容器。",
  },
];